// <auto-generated />
using bobo.orm.efcore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace bobo.orm.efcore.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180103164356_addManager")]
    partial class addManager
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("bobo.entity.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Author");

                    b.Property<int>("Click");

                    b.Property<int>("CommentCount");

                    b.Property<string>("Content");

                    b.Property<string>("Description");

                    b.Property<int>("DiggBad");

                    b.Property<int>("DiggGood");

                    b.Property<string>("From");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("InputAuthor");

                    b.Property<bool>("IsAddRSS");

                    b.Property<bool>("IsBig");

                    b.Property<bool>("IsHot");

                    b.Property<bool>("IsLock");

                    b.Property<bool>("IsMsg");

                    b.Property<bool>("IsRed");

                    b.Property<bool>("IsShow");

                    b.Property<bool>("IsSlide");

                    b.Property<bool>("IsTop");

                    b.Property<string>("LinkUrl");

                    b.Property<int>("RealClick");

                    b.Property<string>("SeoDescription");

                    b.Property<string>("SeoKeywords");

                    b.Property<string>("SeoTitle");

                    b.Property<int>("ShareCount");

                    b.Property<int>("SortId");

                    b.Property<int?>("ThemeId");

                    b.Property<string>("Title");

                    b.Property<string>("Title1");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("bobo.entity.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<int>("CategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategory");
                });

            modelBuilder.Entity("bobo.entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("BackGround");

                    b.Property<string>("CallIndex");

                    b.Property<int?>("CategoryTypeId");

                    b.Property<string>("ClickCount");

                    b.Property<string>("Content");

                    b.Property<int>("GuanZhuCount");

                    b.Property<string>("HeadChar");

                    b.Property<string>("ImgUrl");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsGuoYuan");

                    b.Property<bool>("IsLock");

                    b.Property<string>("LinkUrl");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.Property<string>("PlatformLoginText");

                    b.Property<string>("PlatformLoginUrl");

                    b.Property<string>("PlatformSetUpShopText");

                    b.Property<string>("PlatformSetUpShopUrl");

                    b.Property<int>("RealGuanZhuCount");

                    b.Property<string>("SeoDescription");

                    b.Property<string>("SeoKeywords");

                    b.Property<string>("SeoTitle");

                    b.Property<int>("SortId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("bobo.entity.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AddTime");

                    b.Property<string>("Email");

                    b.Property<int?>("IsDeleted");

                    b.Property<int?>("IsLock");

                    b.Property<string>("RealName");

                    b.Property<int?>("RoleType");

                    b.Property<string>("Telephone");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("roleId");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("bobo.entity.ManagerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionType");

                    b.Property<string>("LoginIp");

                    b.Property<DateTime?>("LoginTime");

                    b.Property<string>("Note");

                    b.Property<string>("UserName");

                    b.Property<int?>("userId");

                    b.HasKey("Id");

                    b.ToTable("ManagerLog");
                });

            modelBuilder.Entity("bobo.entity.ManagerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsDeleted");

                    b.Property<string>("RoleName");

                    b.Property<int?>("RoleType");

                    b.HasKey("Id");

                    b.ToTable("ManagerRole");
                });

            modelBuilder.Entity("bobo.entity.ManagerRoleValue", b =>
                {
                    b.Property<int?>("roleId");

                    b.Property<int?>("channelId");

                    b.Property<string>("ActionType");

                    b.Property<string>("ChannelName");

                    b.Property<int>("Id");

                    b.Property<int?>("ManagerRoleId");

                    b.Property<int?>("SysChannelId");

                    b.HasKey("roleId", "channelId");

                    b.HasIndex("ManagerRoleId");

                    b.HasIndex("SysChannelId");

                    b.ToTable("ManagerRoleValue");
                });

            modelBuilder.Entity("bobo.entity.ManagerSysChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsDeleted");

                    b.Property<string>("LinkUrl");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("SortId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int?>("parentId");

                    b.HasKey("Id");

                    b.HasIndex("parentId");

                    b.ToTable("ManagerSysChannel");
                });

            modelBuilder.Entity("bobo.entity.ArticleCategory", b =>
                {
                    b.HasOne("bobo.entity.Article", "Article")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bobo.entity.Category", "Category")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bobo.entity.Category", b =>
                {
                    b.HasOne("bobo.entity.Category", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("bobo.entity.Manager", b =>
                {
                    b.HasOne("bobo.entity.ManagerRole", "ManagerRole")
                        .WithMany("Managers")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bobo.entity.ManagerRoleValue", b =>
                {
                    b.HasOne("bobo.entity.ManagerRole", "ManagerRole")
                        .WithMany("ManagerRoleValues")
                        .HasForeignKey("ManagerRoleId");

                    b.HasOne("bobo.entity.ManagerSysChannel", "SysChannel")
                        .WithMany("ManagerRoleValues")
                        .HasForeignKey("SysChannelId");
                });

            modelBuilder.Entity("bobo.entity.ManagerSysChannel", b =>
                {
                    b.HasOne("bobo.entity.ManagerSysChannel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parentId");
                });
#pragma warning restore 612, 618
        }
    }
}
